# -*- coding: utf-8 -*-
"""2024.09.04-Hello-world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZGgaPEQcwfHSli7ubzHc9aPHNVfhknql
"""

print("Hello World!")

print("Hello python")

print("우리 모두 파이썬과 친하게 지내 봅시다.")

